create database mydatabase;
use mydatabase;
select *from customer;
#Q1what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue 
from customer 
group by gender;

#Q2 which customer used a discount but still spent more than the avg purchase amt
select customer_id, purchase_amount from customer where discount_applied="Yes" and purchase_amount >=
(select avg(purchase_amount)from customer)

#Q3which are the top 5 products with highest avg review ratings?
select item_purchased,avg(review_rating) as "avg product rating" from customer group by item_purchased
order by avg(review_rating) desc limit 5;

#Q4compare the avg purchase amt between standard and express
select shipping_type,round(avg(purchase_amount),2) from customer 
where shipping_type in ('standard','express') group by shipping_type;

#Q5do subscribed customer spend more? ]compare avg spend and total revenue between subscriber and non subscriber
select subscription_status,count(customer_id) as total_customer,
round(avg(purchase_amount),2) as total_spend,round(sum(purchase_amount),2) as total_revenue from customer
group by subscription_status order by total_revenue,total_spend desc;

#Q6which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,round(100*sum(case when discount_applied="Yes" THEN 1 ELSE 0 END)/COUNT(*),2)
as discount_rate from customer group by item_purchased order by discount_rate desc limit 5;

#Q7segment customer with new ,returning and loyal based on their total no of previous purchases,show the count of each segment

SELECT 
    IF(previous_purchases = 1, 'New',
       IF(previous_purchases BETWEEN 2 AND 10, 'Returning', 'Loyal')
    ) AS customer_segment,
    COUNT(*) AS no_of_customers
FROM customer
GROUP BY customer_segment;

#Q8what are top 5 most purchased products within each category?
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
) AS item_counts
WHERE item_rank <= 3;

#Q9 are customer who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from customer
where previous_purchases>5 group by subscription_status;

#Q10 what is revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue from customer
group by age_group order by total_revenue desc;


ALTER DATABASE mydatabase MODIFY NAME = Analysis;
show tables from data_analysis;